### ISSUE TITLE
SaveFileDialogParams : OneDrive directory  is not displayed

### ISSUE THREAD

**Issue by deacon78** [kineapps/flutter_file_dialog#22] opened 2021-11-25 08:26 UTC
Hello

When entering SaveFileDialogParams, I can see internal Storage, Downloads, external Storage and Google Drive.

But OneDrive is not displayed.

When I use flutter_file_picker which is another package, OneDrive is displayed.

Can you check why OneDrive is not displayed ?

Thank you.

**Comment by deacon78** [comment] 2021-12-02 07:16
up

**Comment by kinex** [comment] 2021-12-03 08:37
Thanks for the bug report. Do you have time to investigate this?

**Comment by deacon78** [comment] 2021-12-03 09:14
Hello kinex
Yes I can help you to investigate this.
Just tell me what to do.
You can reproduce the bug easily : 

1/ install "onedrive" app on an android device (or emulator)
2/ call SaveFileDialogParams from this android device (or emulator)
3/ See that there is only "GoogleDrive" (and obvioulsy SD card, Downloads, Internal Drive) and not "onedrive"

**Comment by kinex** [comment] 2021-12-03 09:32
Actually the issue is most probably that the OneDrive app just doesn't support this. If you try the API `FlutterFileDialog.pickFile`, also OneDrive is there. So you can open files from OneDrive, but saving files is not supported for external apps.

**Comment by deacon78** [comment] 2021-12-03 10:02
Maybe you could open a case to OneDrive App so that the entire ANDROID world users could benefit of that functionality.

**Comment by kinex** [comment] 2021-12-07 19:16
Closing as there is no issue.

**Closed by kinex** 2021-12-07 19:16 UTC
