### ISSUE TITLE
FlutterFileDialog.pickFile doesn't return value if picker is slid down

### ISSUE THREAD

**Issue by aleripe** [kineapps/flutter_file_dialog#14] opened 2021-04-29 15:54 UTC
FlutterFileDialog.pickFile doesn't return value if picker is slid down, instead it does if user taps Cancel. Is this behavior a bug?

**Comment by kinex** [comment] 2021-05-02 18:54
Thanks for the  bug report, fixed in 2.1.0. Let me know if you notice issues.

**Comment by aleripe** [comment] 2021-05-02 19:00
Thanks a lot! You library is really great! 😊

**Comment by marinalvdgs** [comment] 2021-07-26 04:46
Hello @kinex, I still get this issue, have you any suggestions?

**Comment by kinex** [comment] 2021-07-29 08:14
Hi @marinalvdgs, What is your OS version and code sample?

**Comment by marinalvdgs** [comment] 2021-07-29 08:27
@kinex I tested on iOS 14.3 on real devices and iOS 14.5 on a simulator. I try to get file path like this: 
`final params = OpenFileDialogParams();
      final filePath = await FlutterFileDialog.pickFile(params: params);
      if (filePath == null) {
        throw Exception(strings.noFilePicked);
      }
      File f = File(filePath);`
      
And when I close the dialog by pushing the cancel button it's returning null and throwing an exception, but when I trying to close the dialog by swiping down, it doesn't return anything, so my app freezes without throwing any exception. 
Thank you for answering

**Comment by kinex** [comment] 2021-07-29 09:22
Is there any chance that you are using the old version of the plugin? Please try executing `rm Podfile.lock` and `pod install`. Clean also your Flutter project.

**Comment by marinalvdgs** [comment] 2021-07-29 09:55
Yes, I've tried this. In pubspec.yaml I have `flutter_file_dialog: ^2.1.0` and in podfile.lock it's `- flutter_file_dialog (0.0.1)`. Trying to clean and install again doesn't change anything, maybe I need to change something manually?

**Comment by kinex** [comment] 2021-07-29 13:37
I tested this in iOS 13.7. It seems it is not even possible to slide down the document picker in this OS version. You can only press the cancel-button.

**Comment by kinex** [comment] 2021-07-29 14:23
I can reproduce the issue in 14.7.1. The dialog behavior has changed since 13.7, now it is possible to slide down the dialog.

**Closed** 2021-07-29 20:59 UTC

**Comment by kinex** [comment] 2021-07-30 06:53
Fixed in 2.1.1. Thanks for the bug report.

**Comment by marinalvdgs** [comment] 2021-07-30 07:12
Thanks a lot! It works perfectly now ❤️
